FROM openjdk:17-oracle
MAINTAINER venkat venkyjava77@gmail.com
COPY target/spring-boot-docker-image-1.0.0.jar spring-boot-docker-image-1.0.0.jar
ENTRYPOINT ["java","-jar","/spring-boot-docker-image-1.0.0.jar"]
